/*
 * Copyright 2025 WinKernelLite Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// This code was generated by AI (Sonnet 4.0) and manually reviewed for correctness while maintaining backward compatibility with the original API.

#ifndef WINKERNEL_LINKEDLIST_H_
#define WINKERNEL_LINKEDLIST_H_

#include <Windows.h>

static __forceinline
void
InitializeListHead(
    _Out_ PLIST_ENTRY ListHead
)
{
    ListHead->Flink = ListHead->Blink = ListHead;
}

_Must_inspect_result_
static __forceinline
BOOLEAN
IsListEmpty(
    _In_ const LIST_ENTRY* const ListHead
)
{
    return (BOOLEAN)(ListHead->Flink == ListHead);
}

static __forceinline
BOOLEAN
RemoveEntryList(
    _In_ PLIST_ENTRY Entry
)
{
    PLIST_ENTRY const Blink = Entry->Blink;
    PLIST_ENTRY const Flink = Entry->Flink;

    Blink->Flink = Flink;
    Flink->Blink = Blink;
    return (BOOLEAN)(Flink == Blink);
}

static __forceinline
PLIST_ENTRY
RemoveHeadList(
    _Inout_ PLIST_ENTRY ListHead
)
{
    PLIST_ENTRY const Entry = ListHead->Flink;
    PLIST_ENTRY const Flink = Entry->Flink;

    ListHead->Flink = Flink;
    Flink->Blink = ListHead;
    return Entry;
}

static __forceinline
PLIST_ENTRY
RemoveTailList(
    _Inout_ PLIST_ENTRY ListHead
)
{
    PLIST_ENTRY const Entry = ListHead->Blink;
    PLIST_ENTRY const Blink = Entry->Blink;

    ListHead->Blink = Blink;
    Blink->Flink = ListHead;
    return Entry;
}

static __forceinline
void
InsertTailList(
    _Inout_ PLIST_ENTRY ListHead,
    _Inout_ __drv_aliasesMem PLIST_ENTRY Entry
)
{
    PLIST_ENTRY const Blink = ListHead->Blink;

    Entry->Flink = ListHead;
    Entry->Blink = Blink;
    Blink->Flink = Entry;
    ListHead->Blink = Entry;
}

static __forceinline
void
InsertHeadList(
    _Inout_ PLIST_ENTRY ListHead,
    _Inout_ __drv_aliasesMem PLIST_ENTRY Entry
)
{
    PLIST_ENTRY const Flink = ListHead->Flink;

    Entry->Flink = Flink;
    Entry->Blink = ListHead;
    Flink->Blink = Entry;
    ListHead->Flink = Entry;
}

static __forceinline
void
AppendTailList(
    _Inout_ PLIST_ENTRY ListHead,
    _Inout_ PLIST_ENTRY ListToAppend
)
{
    // If the list to append is empty (Flink points to self), nothing to do
    if (ListToAppend->Flink == ListToAppend) {
        return;
    }

    PLIST_ENTRY const FirstNew = ListToAppend->Flink;     // First node of list to append
    PLIST_ENTRY const LastNew = ListToAppend->Blink;      // Last node of list to append
    PLIST_ENTRY const LastOld = ListHead->Blink;          // Last node of original list

    // Connect end of original list to start of appended list
    LastOld->Flink = FirstNew;
    FirstNew->Blink = LastOld;

    // Connect end of appended list to list head
    LastNew->Flink = ListHead;
    ListHead->Blink = LastNew;
}

#endif


